## ----setup, include=FALSE------------------------------------------------
knitr::opts_chunk$set(echo = TRUE)

## ----install packages, echo=FALSE, warning=FALSE, results='hide',message=FALSE----

###*****************************
# INITIAL COMMANDS TO RESET THE SYSTEM
rm(list = ls())
if (is.integer(dev.list())){dev.off()}
cat("\014")
seedNo=14159
set.seed(seedNo)
###*****************************

###*****************************
require("sicegar")
require("dplyr")
require("ggplot2")
require("cowplot")
###*****************************

## ----generate data for sigmoidal-----------------------------------------
time=seq(3,24,0.5)

#simulate intensity data and add noise
noise_parameter=0.1
intensity_noise=stats::runif(n = length(time),min = 0,max = 1)*noise_parameter
intensity=sicegar::sigmoidalFitFormula(time, maximum=4, slopeParam=1, midPoint=8)
intensity=intensity+intensity_noise

dataInputSigmoidal=data.frame(intensity=intensity,time=time)

## ----generate data for double - sigmoidal--------------------------------
noise_parameter=0.2
intensity_noise=runif(n = length(time),min = 0,max = 1)*noise_parameter
intensity = sicegar::doublesigmoidalFitFormula(time,
                                    finalAsymptoteIntensityRatio=.3,
                                    maximum=4,
                                    slope1Param=1,
                                    midPoint1Param=7,
                                    slope2Param=1,
                                    midPointDistanceParam=8)
intensity=intensity+intensity_noise
dataInputDoubleSigmoidal=data.frame(intensity=intensity,time=time)

## ----apply fitFunction for sigmoidal & double_sigmoidal datasets---------
fitObj_sm <- fitFunction(dataInput = dataInputSigmoidal)
fitObj_dsm <- fitFunction(dataInput = dataInputDoubleSigmoidal)

## ----The results of the sigmoidal fit------------------------------------

# Normalized data generated by a sigmoidal model
print(fitObj_sm$normalizedInput)

# Parameters of sigmoidal fit for data generated by a sigmoidal model. For details look at "sigmoidal_vignette" and "parameterCalculation_vignette".
print(t(fitObj_sm$sigmoidalModel))

# Parameters of double_sigmoidal fit for data generated by a sigmoidal model. For details look at "double_sigmoidal_vignette" and "parameterCalculation_vignette".
print(t(fitObj_sm$doubleSigmoidalModel))

# comparison of sigmoidal and double_sigmoidal models for data generated by a sigmoidal model. Sigmoidal model is the winner. For details of the parameters look at "categorize_vignette"
utils::str(fitObj_sm$outputCluster)

## ----The results of the double_sigmoidal fit-----------------------------

# Normalized data generated by a double_sigmoidal model
print(fitObj_dsm$normalizedInput)

# Parameters of sigmoidal fit for data generated by a double_sigmoidal model. For details look at "sigmoidal_vignette" and "parameterCalculation_vignette".
print(t(fitObj_dsm$sigmoidalModel))

# Parameters of double_sigmoidal fit for data generated by a double_sigmoidal model. For details look at "double_sigmoidal_vignette" and "parameterCalculation_vignette".
print(t(fitObj_dsm$doubleSigmoidalModel))

# comparison of sigmoidal and double_sigmoidal models for data generated by a double_sigmoidal model. double_sigmoidal model is the winner. For details of the parameters look at "categorize_vignette"
utils::str(fitObj_dsm$outputCluster)

## ----cowplor figure, echo=TRUE, message=FALSE, warning=FALSE, comment=FALSE, fig.height=4, fig.width=8----
fig_a=sicegar::figureModelCurves(dataInput=fitObj_sm$normalizedInput,
                                  sigmoidalFitVector=fitObj_sm$sigmoidalModel,
                                  showParameterRelatedLines=TRUE)

# Double Sigmoidal Fit with parameter related lines
fig_b=sicegar::figureModelCurves(dataInput=fitObj_dsm$normalizedInput,
                                  doubleSigmoidalFitVector=fitObj_dsm$doubleSigmoidalModel,
                                  showParameterRelatedLines=TRUE)

fig <- cowplot::plot_grid(fig_a, fig_b, ncol = 2)
print(fig)

