#' @title doublesigmoidalFitFunction
#'
#' @param dataInput dataInput should be a data frame composed of two columns. One is for time other is for intensity. Or it should be a normalized data generated by normalizeData function
#' @param tryCounter is the input that represent the number of the call of this function for the same situation.
#' @param startList The initial set of parameters that algorithm tries for the fit. Where the parameters are 'maximumValue' that represents the maximum value that the function that can take, 'slope1' that represents the maximum slope in normalized y axis at the exponential phase, 'midPoint1' that represents the x axis value for maximum slope in exponential phase, 'slope2' that represents the maximum slope in normalized y axis during lysis, 'midPointDistance' that represents the x axis distance between maximum slope in exponential phase and maximum slope in lysis, 'finalAsymptoteIntensity' represents the intensity value at time is infinite as the ratio with respect to maximum value reached so it should be a number between 0 and 1.
#' @param lowerBounds The lower bouns for the randomly generated start parameters and also for the search space that the program runs. The elements of the vector are 'maximum' that represents the maximum value that the function that can take, 'slope1' that represents the maximum slope in normalized y axis at the exponential phase, 'midPoint1' that represents the x axis value for maximum slope in exponential phase,'slope2' that represents the maximum slope in normalized y axis during lysis, 'midPointDistance' that represents the x axis distance between maximum slope in exponential phase and maximum slope in lysis, 'finalAsymptoteIntensity' represents the intensity value at time is infiniteas the ratio with respect to maximum value reached so it should be a number between 0 and 1.
#' @param upperBounds The lower bouns for the randomly generated start parameters and also for the search space that the program runs. The elements of the vector are 'maximum' that represents the maximum value that the function that can take, 'slope1' that represents the maximum slope in normalized y axis at the exponential phase, 'midPoint1' that represents the x axis value for maximum slope in exponential phase, 'slope2' that represents the maximum slope in normalized y axis during lysis, 'midPointDistance' that represents the x axis distance between maximum slope in exponential phase and maximum slope in lysis, 'finalAsymptoteIntensity' represents the intensity value at time is infiniteas the ratio with respect to maximum value reached so it should be a number between 0 and 1.
#' @param min_Factor define minimum step size in the iterations
#' @param n_iterations define maximum number of iterations for a run
#'
#' @return Function returns fitted parameters for lineFit. The slope, intersection and parameters related with quality of the fit
#' @export
#'
#' @examples
#' # Related example
#'
#'# Initial Command to Reset the System
#'rm(list = ls())
#'if (is.integer(dev.list())){dev.off()}
#'cat("\014")
#'
#'time=seq(3,24,0.1)
#'
#'#intensity with Noise
#'noise_parameter=0.2
#'intensity_noise=runif(n = length(time),min = 0,max = 1)*noise_parameter
#'intensity=doublesigmoidalFitFormula(time,
#'                                    finalAsymptoteIntensity=.3,
#'                                    maximum=4,
#'                                    slope1=1,
#'                                    midPoint1=7,
#'                                    slope2=1,
#'                                    midPointDistance=8)
#'intensity=intensity+intensity_noise
#'
#'dataInput=data.frame(intensity=intensity,time=time)
#'dataOutput = normalizeData(dataInput)
#'dataInput2=dataOutput
#'parameterVector<-doublesigmoidalFitFunction(dataInput2,tryCounter=2)
#'
#'
#'#Check the results
#'if(parameterVector$isThisaFit){
#'  intensityTheoretical=doublesigmoidalFitFormula(time,
#'                                                 finalAsymptoteIntensity=parameterVector$finalAsymptoteIntensity_Estimate,
#'                                                 maximum=parameterVector$maximum_Estimate,
#'                                                 slope1=parameterVector$slope1_Estimate,
#'                                                 midPoint1=parameterVector$midPoint1_Estimate,
#'                                                 slope2=parameterVector$slope2_Estimate,
#'                                                 midPointDistance=parameterVector$midPointDistance_Estimate)
#'
#'  comparisonData=cbind(dataInput,intensityTheoretical)
#'  require(ggplot2)
#'  ggplot(comparisonData)+
#'    geom_point(aes(x=time, y=intensity))+
#'    geom_line(aes(x=time,y=intensityTheoretical))+
#'    expand_limits(x = 0, y = 0)}
#'
#'if(!parameterVector$isThisaFit){print(parameterVector)}
#'
doublesigmoidalFitFunction<-function(dataInput,
                                  tryCounter,
                                  startList=list(finalAsymptoteIntensity = 0,
                                                 maximum = 1,
                                                 slope1 = 1,
                                                 midPoint1 = 0.3333333,
                                                 slope2=1,
                                                 midPointDistance=0.2916667),
                                  lowerBounds=c(finalAsymptoteIntensity = 0,
                                                maximum = 0.3,
                                                slope1 = .01,
                                                midPoint1 = -0.5208333,
                                                slope2=.01,
                                                midPointDistance=0.04166667),
                                  upperBounds=c(finalAsymptoteIntensity = 1,
                                                maximum = 1.5,
                                                slope1 = 120,
                                                midPoint1 = 1.145833,
                                                slope2=120,
                                                midPointDistance=0.625),
                                  min_Factor=1/2^20,
                                  n_iterations=500)
{

  isalist=(is.list(dataInput) & !is.data.frame(dataInput))
  if(isalist){dataFrameInput=dataInput$timeIntensityData}
  isadataframe=(is.data.frame(dataInput))
  if(isadataframe){dataFrameInput=dataInput}

  if(tryCounter==1){counterDependentStartList=startList}
  if(tryCounter!=1){
    randomVector=runif(length(startList), 0, 1)
    names(randomVector)<-c("finalAsymptoteIntensity",
                           "maximum",
                           "slope1",
                           "midPoint1",
                           "slope2",
                           "midPointDistance")
    counterDependentStartVector=randomVector*(upperBounds-lowerBounds)+lowerBounds
    counterDependentStartList=as.list(counterDependentStartVector)}


  theFitResult <- try(minpack.lm::nlsLM(intensity ~ sicegar::doublesigmoidalFitFormula(time,
                                                                                       finalAsymptoteIntensity,
                                                                                       maximum,
                                                                                       slope1,
                                                                                       midPoint1,
                                                                                       slope2,
                                                                                       midPointDistance),
                                        dataFrameInput,
                                        start=counterDependentStartList,
                                        control = list(maxiter = n_iterations, minFactor = min_Factor),
                                        lower = lowerBounds,
                                        upper = upperBounds,
                                        trace=F),silent = TRUE)

  if(class(theFitResult)!="try-error")
  {
    parameterMatrix=summary(theFitResult)$parameters
    colnames(parameterMatrix)<-c("Estimate","Std_Error","t_value","Pr_t")

    parameterVector=c(t(parameterMatrix))
    names(parameterVector)<- c("finalAsymptoteIntensity_N_Estimate","finalAsymptoteIntensity_Std_Error","finalAsymptoteIntensity_t_value","finalAsymptoteIntensity_Pr_t",
                               "maximum_N_Estimate","maximum_Std_Error","maximum_t_value","maximum_Pr_t",
                               "slope1_N_Estimate","slope1_Std_Error","slope1_t_value","slope1_Pr_t",
                               "midPoint1_N_Estimate","midPoint1_Std_Error","midPoint1_t_value","midPoint1_Pr_t",
                               "slope2_N_Estimate","slope2_Std_Error","slope2_t_value","slope2_Pr_t",
                               "midPointDistance_N_Estimate","midPointDistance_Std_Error","midPointDistance_t_value","midPointDistance_Pr_t")

    parameterVector<-c(parameterVector,
                       residual_Sum_of_Squares=sum((as.vector(resid(theFitResult)))^2)[1],
                       log_likelihood=as.vector(logLik(theFitResult))[1],
                       AIC_value=as.vector(AIC(theFitResult))[1],
                       BIC_value=as.vector(BIC(theFitResult))[1])

    parameterList=as.list(parameterVector)
    parameterList$isThisaFit=TRUE
    parameterList$startVector=counterDependentStartList
    if(isalist){parameterList$dataScalingParameters=as.list(dataInput$dataScalingParameters)}
    parameterList$model="doublesigmoidal"
    parameterList$numericalParameters=FALSE


    parameterDf=as.data.frame(parameterList)
    #Renormalize Parameters
    parameterDf=doublesigmoidalRenormalizeParameters(parameterDf,isalist)

  }

  if(class(theFitResult)=="try-error")
  {
    parameterVector=rep(NA, 24)
    names(parameterVector)<- c("finalAsymptoteIntensity_N_Estimate","finalAsymptoteIntensity_Std_Error","finalAsymptoteIntensity_t_value","finalAsymptoteIntensity_Pr_t",
                               "maximum_N_Estimate","maximum_Std_Error","maximum_t_value","maximum_Pr_t",
                               "slope1_N_Estimate","slope1_Std_Error","slope1_t_value","slope1_Pr_t",
                               "midPoint1_N_Estimate","midPoint1_Std_Error","midPoint1_t_value","midPoint1_Pr_t",
                               "slope2_N_Estimate","slope2_Std_Error","slope2_t_value","slope2_Pr_t",
                               "midPointDistance_N_Estimate","midPointDistance_Std_Error","midPointDistance_t_value","midPointDistance_Pr_t")

    parameterVector<-c(parameterVector,
                       residual_Sum_of_Squares=Inf,
                       log_likelihood=NA,
                       AIC_value=NA,
                       BIC_value=NA)

    parameterList=as.list(parameterVector)
    parameterList$isThisaFit=FALSE
    parameterList$startVector=counterDependentStartList
    if(isalist){parameterList$dataScalingParameters=as.list(dataInput$dataScalingParameters)}
    parameterList$model="doublesigmoidal"

    parameterDf=as.data.frame(parameterList)
    #Renormalize Parameters
    parameterDf=doublesigmoidalRenormalizeParameters(parameterDf,isalist)

  }

  return(parameterDf)

}
#**************************************


#**************************************
# @title doublesigmoidalFitFormula
#
# @param x is the "time" (time) column of the dataframe
#
# @param finalAsymptoteIntensity represents the intensity value at time is infinite.
# @param maximum is the maximum value that the sigmoidal function can reach
# @param slope1 is the slope of the sigmoidal function at the steppest point
# @param midPoint1 is the x axis value of the steppest point in the function
#
# @return the function returns the predicted intensities for given time points in the double-sigmoidal fit model
#
# @examples
#' @export
doublesigmoidalFitFormula<-function(x,
                                    finalAsymptoteIntensity,
                                    maximum,
                                    slope1,
                                    midPoint1,
                                    slope2,
                                    midPointDistance)
{
  if(slope1<0){stop("slope1 should be a positive number")}
  if(slope2<0){stop("slope2 should be a positive number. It is the absolute value of the second slope")}
  if(midPointDistance<0){stop("midPointDistance should be a positive number. It is the distance between two steppest points of exponential phase and lysis")}
  if(finalAsymptoteIntensity<0 | finalAsymptoteIntensity>1){stop("finalAsymptoteIntensity should be a number between 0 and 1")}
  if(maximum<0){stop("maximum should be a positive number")}

  optimizeIntervalMin=midPoint1-2*midPointDistance
  optimizeIntervalMax=midPoint1+3*midPointDistance
  xmax <- optimize(f1,
                   c(optimizeIntervalMin,optimizeIntervalMax),
                   tol=0.0001,
                   B1=slope1, M1=midPoint1, B2=slope2, L=midPointDistance, maximum = TRUE);
  argumentt=xmax$maximum;
  constt=f0(argumentt, slope1, midPoint1, slope2, midPointDistance);
  y=f2(x,
       finalAsymptoteIntensity, maximum,
       slope1, midPoint1,
       slope2, midPointDistance,
       constt, argumentt);
  return(y)}
#**************************************


#**************************************
#' @export
f0 <- function (x, B1, M1, B2, L) {
  (1/( ( 1+exp(-B1*(x-M1)) ) * ( 1+exp(B2*(x-(M1+L))) ) ))}
#' @export
f1 <- function (x, B1, M1, B2, L) {
  log((1/( ( 1+exp(-B1*(x-M1)) ) * ( 1+exp(B2*(x-(M1+L))) ) )))}
#' @export
f2 <- function (x, A2, Ka, B1, M1, B2, L, const, argument)
{ fBasics::Heaviside(x-argument)* ( f0(x, B1, M1, B2, L)* ((Ka-A2*Ka)/(const)) + A2*Ka) +
    (1-fBasics::Heaviside(x-argument))* ( f0(x, B1, M1, B2, L)* ((Ka-0*Ka)/(const)) + 0*Ka)}
#' @export
f0mid <- function (x, B1, M1, B2, L,const) {
  -const/2+1/( ( 1+exp(-B1*(x-M1)) ) * ( 1+exp(B2*(x-(M1+L))) ) )}
#**************************************


#**************************************
#' @title f_argmax_doublesigmoidal
#' @return return the x value of the maximum
#' @export
f_argmax_doublesigmoidal <- function(parameterVector){

  max_x = parameterVector$dataScalingParameters.timeRatio
  xmax <- optimize(f1,
                   c(0,max_x),
                   tol=0.0001,
                   B1=parameterVector$slope1_Estimate,
                   M1=parameterVector$midPoint1_Estimate,
                   B2=parameterVector$slope2_Estimate ,
                   L=parameterVector$midPointDistance_Estimate,
                   maximum = TRUE);
  argumentt=xmax$maximum;
  return(argumentt)}
#**************************************


#**************************************
#' @title f_mid1_doublesigmoidal
#' @return return the x values of midpoint1, by assuming the y of midpoint1 is the half of the maximum value it reaches
#' @export
f_mid1_doublesigmoidal <- function(parameterVector){

  max_x = parameterVector$dataScalingParameters.timeRatio
  xmax <- optimize(f1,
                   interval=c(-0.5208333*max_x,max_x*(1.145833+0.625)),
                   tol=0.0001,
                   B1=parameterVector$slope1_Estimate,
                   M1=parameterVector$midPoint1_Estimate,
                   B2=parameterVector$slope2_Estimate ,
                   L=parameterVector$midPointDistance_Estimate,
                   maximum = TRUE);
  argumentt=xmax$maximum;
  constt=f0(argumentt,
            B1=parameterVector$slope1_Estimate,
            M1=parameterVector$midPoint1_Estimate,
            B2=parameterVector$slope2_Estimate ,
            L=parameterVector$midPointDistance_Estimate);

  mid1x <- uniroot(f0mid,
                   interval=c(-0.5208333*max_x,argumentt),
                   tol=0.0001,
                   B1=parameterVector$slope1_Estimate,
                   M1=parameterVector$midPoint1_Estimate,
                   B2=parameterVector$slope2_Estimate ,
                   L=parameterVector$midPointDistance_Estimate,
                   const=constt);
  mid1x=mid1x$root
  return(mid1x)}
#**************************************


#**************************************
#' @title f_mid2_doublesigmoidal
#' @return return the x values of midpoint2, by assuming the y of midpoint2 is the half of the distance between maximum value it reaches and final asymptote
#' @export
f_mid2_doublesigmoidal <- function(parameterVector){

  max_x = parameterVector$dataScalingParameters.timeRatio
  xmax <- optimize(f1,
                   interval=c(-0.5208333*max_x,max_x*(1.145833+0.625)),
                   tol=0.0001,
                   B1=parameterVector$slope1_Estimate,
                   M1=parameterVector$midPoint1_Estimate,
                   B2=parameterVector$slope2_Estimate ,
                   L=parameterVector$midPointDistance_Estimate,
                   maximum = TRUE);

  argumentt=xmax$maximum;
  constt=f0(argumentt,
            B1=parameterVector$slope1_Estimate,
            M1=parameterVector$midPoint1_Estimate,
            B2=parameterVector$slope2_Estimate ,
            L=parameterVector$midPointDistance_Estimate);

  mid2x <- uniroot(f0mid, interval=c(argumentt,max_x*(1.145833+0.625)),
                   tol=0.0001,
                   B1=parameterVector$slope1_Estimate,
                   M1=parameterVector$midPoint1_Estimate,
                   B2=parameterVector$slope2_Estimate ,
                   L=parameterVector$midPointDistance_Estimate,
                   const=constt);
  mid2x=mid2x$root
  return(mid2x)}
#**************************************


#**************************************
# calculate slope (5 points derivative)
#' @title Numerical Slope of Double Sigmoidal
#' @return return the numerical slope of double sigmoidal for the given x value
#' @export
fslope_doublesigmoidal <- function(x, parameterVector, timeStep=0.00001){

  fxp2h=doublesigmoidalFitFormula(x=x+2*timeStep,
                                  finalAsymptoteIntensity=parameterVector$finalAsymptoteIntensity_Estimate,
                                  maximum=parameterVector$maximum_Estimate,
                                  slope1=parameterVector$slope1_Estimate,
                                  midPoint1=parameterVector$midPoint1_Estimate,
                                  slope2=parameterVector$slope2_Estimate,
                                  midPointDistance=parameterVector$midPointDistance_Estimate)
  fxph=doublesigmoidalFitFormula(x=x+timeStep,
                                  finalAsymptoteIntensity=parameterVector$finalAsymptoteIntensity_Estimate,
                                  maximum=parameterVector$maximum_Estimate,
                                  slope1=parameterVector$slope1_Estimate,
                                  midPoint1=parameterVector$midPoint1_Estimate,
                                  slope2=parameterVector$slope2_Estimate,
                                  midPointDistance=parameterVector$midPointDistance_Estimate)

  fxmh=doublesigmoidalFitFormula(x=x-timeStep,
                                  finalAsymptoteIntensity=parameterVector$finalAsymptoteIntensity_Estimate,
                                  maximum=parameterVector$maximum_Estimate,
                                  slope1=parameterVector$slope1_Estimate,
                                  midPoint1=parameterVector$midPoint1_Estimate,
                                  slope2=parameterVector$slope2_Estimate,
                                  midPointDistance=parameterVector$midPointDistance_Estimate)

  fxm2h=doublesigmoidalFitFormula(x=x-2*timeStep,
                                  finalAsymptoteIntensity=parameterVector$finalAsymptoteIntensity_Estimate,
                                  maximum=parameterVector$maximum_Estimate,
                                  slope1=parameterVector$slope1_Estimate,
                                  midPoint1=parameterVector$midPoint1_Estimate,
                                  slope2=parameterVector$slope2_Estimate,
                                  midPointDistance=parameterVector$midPointDistance_Estimate)

  der=(-1*fxp2h+8*fxph-8*fxmh+1*fxm2h)/(12*timeStep)
  return(der)
}
#**************************************


#**************************************
#' @export
doublesigmoidalRenormalizeParameters<-function(parameterDF,isalist)
{
  if(isalist){
    parameterDF$finalAsymptoteIntensity_Estimate=parameterDF$finalAsymptoteIntensity_N_Estimate
    parameterDF$maximum_Estimate=parameterDF$maximum_N_Estimate*parameterDF$dataScalingParameters.intensityRatio+parameterDF$dataScalingParameters.intensityMin
    parameterDF$slope1_Estimate=parameterDF$slope1_N_Estimate/parameterDF$dataScalingParameters.timeRatio
    parameterDF$midPoint1_Estimate=parameterDF$midPoint1_N_Estimate*parameterDF$dataScalingParameters.timeRatio
    parameterDF$slope2_Estimate=parameterDF$slope2_N_Estimate/parameterDF$dataScalingParameters.timeRatio
    parameterDF$midPointDistance_Estimate=parameterDF$midPointDistance_N_Estimate*parameterDF$dataScalingParameters.timeRatio
    }
  if(!isalist){
    parameterDF$finalAsymptoteIntensity_Estimate=parameterDF$finalAsymptoteIntensity_N_Estimate
    parameterDF$maximum_Estimate=parameterDF$maximum_N_Estimate
    parameterDF$slope1_Estimate=parameterDF$slope1_N_Estimate
    parameterDF$midPoint1_Estimate=parameterDF$midPoint1_N_Estimate
    parameterDF$slope2_Estimate=parameterDF$slope2_N_Estimate
    parameterDF$midPointDistance_Estimate=parameterDF$midPointDistance_N_Estimate
    }
  return(parameterDF)
}
#**************************************
