#' @title sigmoidalFunction
#'
#' @param dataInput dataInput should be a data frame composed of two columns. One is for time other is for intensity. Or it should be a normalized data generated by normalizeData function
#' @param tryCounter is the input that represent the number of the call of this function for the same situation.
#' @param startList The initial set of parameters that algorithm tries for the fit. Where the parameters are 'maximumValue' that represents the maximum value that the function that can take,  'slopeValue' that represents the slope in normalized y axis, 'midPointValue' that represents midpoint.
#' @param lowerBounds The lower bouns for the randomly generated start parameters. The elements of the vector are  'maximumValue' that represents the maximum value that the function that can take,  'slopeValue' that represents the slope in normalized y axis, 'midPointValue' that represents midpoint
#' @param upperBounds The lower bouns for the randomly generated start parameters. The elements of the vector are  'maximumValue' that represents the maximum value that the function that can take,  'slopeValue' that represents the slope in normalized y axis, 'midPointValue' that represents midpoint
#' @param min_Factor define minimum step size in the iterations
#' @param n_iterations define maximum number of iterations for a run
#'
#' @return Function returns fitted parameters for lineFit. The slope, intersection and parameters related with quality of the fit
#' @export
#'
#' @examples
#' # related examples
#'
#'# Initial Command to Reset the System
#'rm(list = ls())
#'if (is.integer(dev.list())){dev.off()}
#'cat("\014")
#'
#'time=seq(3,24,0.5)
#'
#'#intensity with Noise
#'noise_parameter=0.1
#'intensity_noise=runif(n = length(time),min = 0,max = 1)*noise_parameter
#'intensity=sigmoidalFitFormula(time, maximum=4, slope=1, midPoint=8)
#'intensity=intensity+intensity_noise
#'
#'dataInput=data.frame(intensity=intensity,time=time)
#'dataOutput = normalizeData(dataInput)
#'dataInput2=dataOutput
#'parameterVector<-sigmoidalFunction(dataInput2,tryCounter=2)
#'
#'#Check the results
#'if(parameterVector$isThisaFit){
#'intensityTheoretical=sigmoidalFitFormula(time,
#'                                         maximum=parameterVector$maximum_Estimate,
#'                                         slope=parameterVector$slope_Estimate,
#'                                         midPoint=parameterVector$midPoint_Estimate)
#'
#'comparisonData=cbind(dataInput,intensityTheoretical)
#'ggplot(comparisonData)+
#'  geom_point(aes(x=time, y=intensity))+
#'  geom_line(aes(x=time,y=intensityTheoretical))+
#'  expand_limits(x = 0, y = 0)}
#'
#'if(!parameterVector$isThisaFit){print(parameterVector)}
#'
sigmoidalFunction<-function(dataInput,
                            tryCounter,
                            startList=list(maximum = 1, slope = 1, midPoint = 0.3333333),
                            lowerBounds=c(maximum=0.3, slope=0.01,  midPoint=0.3125-0.8333333),
                            upperBounds=c(maximum=1.5, slope=50,  midPoint=0.3125+0.8333333),
                            min_Factor=1/2^20,
                            n_iterations=500)
{

  isalist=(is.list(dataInput) & !is.data.frame(dataInput))
  if(isalist){dataFrameInput=dataInput$timeIntensityData}
  isadataframe=(is.data.frame(dataInput))
  if(isadataframe){dataFrameInput=dataInput}

  if(tryCounter==1){counterDependentStartList=startList}
  if(tryCounter!=1){
    randomVector=runif(length(startList), 0, 1)
    names(randomVector)<-c("maximum", "slope", "midPoint")
    counterDependentStartVector=randomVector*(upperBounds-lowerBounds)+lowerBounds
    counterDependentStartList=as.list(counterDependentStartVector)}

  theFitResult <- try(minpack.lm::nlsLM(intensity ~ sicegar::sigmoidalFitFormula(time, maximum, slope, midPoint),
                                        dataFrameInput,
                                        start=counterDependentStartList,
                                        control = list(maxiter = n_iterations, minFactor = min_Factor),
                                        lower = lowerBounds,
                                        upper = upperBounds,
                                        trace=F))

  if(class(theFitResult)!="try-error")
  {
    parameterMatrix=summary(theFitResult)$parameters
    colnames(parameterMatrix)<-c("Estimate","Std_Error","t_value","Pr_t")

    parameterVector=c(t(parameterMatrix))
    names(parameterVector)<- c("maximum_N_Estimate","maximum_Std_Error","maximum_t_value","maximum_Pr_t",
                               "slope_N_Estimate","slope_Std_Error","slope_t_value","slope_Pr_t",
                               "midPoint_N_Estimate","midPoint_Std_Error","midPoint_t_value","midPoint_Pr_t")

    parameterVector<-c(parameterVector,
                       residual_Sum_of_Squares=sum((as.vector(resid(theFitResult)))^2)[1],
                       log_likelihood=as.vector(logLik(theFitResult))[1],
                       AIC_value=as.vector(AIC(theFitResult))[1],
                       BIC_value=as.vector(BIC(theFitResult))[1])

    parameterList=as.list(parameterVector)
    parameterList$isThisaFit=TRUE
    parameterList$startVector=counterDependentStartList
    if(isalist){parameterList$dataScalingParameters=as.list(dataInput$dataScalingParameters)}
    parameterList$model="sigmoidal"

    parameterDf=as.data.frame(parameterList)
    #Renormalize Parameters
    parameterDf=sigmoidalRenormalizeParameters(parameterDf,isalist)

  }

  if(class(theFitResult)=="try-error")
  {
    parameterVector=rep(NA, 12)
    names(parameterVector)<- c("maximum_N_Estimate","maximum_Std_Error","maximum_t_value","maximum_Pr_t",
                               "slope_N_Estimate","slope_Std_Error","slope_t_value","slope_Pr_t",
                               "midPoint_N_Estimate","midPoint_Std_Error","midPoint_t_value","midPoint_Pr_t")

    parameterVector<-c(parameterVector,
                       residual_Sum_of_Squares=Inf,
                       log_likelihood=NA,
                       AIC_value=NA,
                       BIC_value=NA)

    parameterList=as.list(parameterVector)
    parameterList$isThisaFit=FALSE
    parameterList$startVector=counterDependentStartList
    if(isalist){parameterList$dataScalingParameters=as.list(dataInput$dataScalingParameters)}
    parameterList$model="sigmoidal"

    parameterDf=as.data.frame(parameterList)
    #Renormalize Parameters
    parameterDf=sigmoidalRenormalizeParameters(parameterDf,isalist)


  }

  return(parameterDf)
}


# @title sigmoidalFitFormula
#
# @param x is the "time" (time) column of the dataframe
# @param maximum is the maximum value that the sigmoidal function can reach
# @param slope is the slope of the sigmoidal function at the steppest point
# @param midPoint is the x axis value of the steppest point in the function
#
# @return the function returns the predicted intensities for given time points in the sigmoidal fit model
#
# @examples
#' @export
sigmoidalFitFormula<-function(x, maximum, slope, midPoint){
  y=(0 + (maximum - 0)/(1 + exp((-slope)*(x - midPoint))));
  return(y)}

#' @export
sigmoidalRenormalizeParameters<-function(parameterDF,isalist)
{
  if(isalist){
    parameterDF$maximum_Estimate=parameterDF$maximum_N_Estimate*parameterDF$dataScalingParameters.intensityRatio+parameterDF$dataScalingParameters.intensityMin
    parameterDF$slope_Estimate=parameterDF$slope_N_Estimate/parameterDF$dataScalingParameters.timeRatio
    parameterDF$midPoint_Estimate=parameterDF$midPoint_N_Estimate*parameterDF$dataScalingParameters.timeRatio
  }
  if(!isalist){
    parameterDF$maximum_Estimate=parameterDF$maximum_N_Estimate
    parameterDF$slope1_Estimate=parameterDF$slope_N_Estimate
    parameterDF$midPoint_Estimate=parameterDF$midPoint_N_Estimate
  }
  return(parameterDF)
}
